const donors = [
  {
    name: "Marufa ",
    age: 30,
    location: "N.gnj",
    phone: "0178000000",
    blood_group: "B+",
    isMarried: true,
    last_donate_date: 500,
    histry_of_donation: [
      {
        name: "Marufa ",
        donate_date: 1000,
        location: "Natore",
        isMarried: true,
        total_donation: 2,
      },
      {
        name: "Marufa ",
        donate_date: 1600,
        location: "Natore",
        isMarried: true,
        total_donation: 2,
      },
    ],
  },
  {
    name: "Pia ",
    age: 30,
    location: "Khulna",
    phone: 400,
    blood_group: "A+",
    isMarried: false,
    last_donate_date: 800,
    histry_of_donation: [
      {
        name: "Pia",
        donate_date: 1200,
        location: "Natore",
        isMarried: true,
        total_donation: 3,
      },
      {
        name: "Pia",
        donate_date: 1600,
        location: "Natore",
        isMarried: true,
        total_donation: 3,
      },
      {
        name: "Pia",
        donate_date: 2000,
        location: "Natore",
        isMarried: true,
        total_donation: 3,
      },
    ],
  },
  {
    name: "Lipa ",
    age: 30,
    location: "Jessore",
    phone: "0178000003",
    blood_group: "O+",
    isMarried: true,
    last_donate_date: 120,
    histry_of_donation: [
      {
        name: "Lipa ",
        donate_date: 400,
        location: "Jessore",
        isMarried: true,
        total_donation: 0,
      },
    ],
  },
  {
    name: "Suma ",
    age: 30,
    location: "Rajshahi",
    phone: "0178000004",
    blood_group: "AB+",
    isMarried: false,
    last_donate_date: 200,
    histry_of_donation: [
      {
        name: "Suma ",
        donate_date: 400,
        location: "Rajshahi",
        isMarried: true,
        total_donation: 1,
      },
    ],
  },
  {
    name: "Habib ",
    age: 30,
    location: "N.gnj",
    phone: "0178000000",
    blood_group: "B+",
    isMarried: true,
    last_donate_date: 105,
    histry_of_donation: [
      {
        name: "Habib ",
        donate_date: 250,
        location: "Natore",
        isMarried: true,
        total_donation: 1,
      },
    ],
  },
  {
    name: "Rina ",
    age: 30,
    location: "N.gnj",
    phone: "0178000000",
    blood_group: "B+",
    isMarried: true,
    last_donate_date: 300,
    histry_of_donation: [
      {
        name: "Rina ",
        donate_date: 600,
        location: "Natore",
        isMarried: true,
        total_donation: 1,
      },
    ],
  },
  {
    name: "Uzzal ",
    age: 30,
    location: "N.gnj",
    phone: "0178000000",
    blood_group: "B+",
    isMarried: true,
    last_donate_date: 500,
    histry_of_donation: [
      {
        name: "Uzzal ",
        donate_date: 800,
        location: "Natore",
        isMarried: true,
        total_donation: 1,
      },
    ],
  },
  {
    name: "Sohel ",
    age: 30,
    location: "N.gnj",
    phone: "0178000000",
    blood_group: "B+",
    isMarried: true,
    last_donate_date: 100,
    histry_of_donation: [
      {
        name: "Sohel ",
        donate_date: 300,
        location: "Natore",
        isMarried: true,
        total_donation: 1,
      },
    ],
  },
  {
    name: "Sazzad ",
    age: 30,
    location: "N.gnj",
    phone: "0178000000",
    blood_group: "B+",
    isMarried: true,
    last_donate_date: 110,
    histry_of_donation: [
      {
        name: "Sazzad ",
        donate_date: 300,
        location: "Natore",
        isMarried: true,
        total_donation: 1,
      },
    ],
  },
  {
    name: "Saddam ",
    age: 30,
    location: "N.gnj",
    phone: "0178000000",
    blood_group: "B+",
    isMarried: true,
    last_donate_date: 10,
    histry_of_donation: [
      {
        name: "Saddam ",
        donate_date: 200,
        location: "Natore",
        isMarried: true,
        total_donation: 1,
      },
    ],
  },
];
