//  let studentsDatabase = [
//    {
//      name: "John",
//      roll: "001",
//      registration: "2021001",
//      gender: "Male",
//      marks: {
//        Math: { obtainedMarks: 85, grade: "A" },
//        Science: { obtainedMarks: 90, grade: "A+" },
//        English: { obtainedMarks: 80, grade: "A-" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "Alice",
//      roll: "002",
//      registration: "2021002",
//      gender: "Female",
//      marks: {
//        Math: { obtainedMarks: 90, grade: "A+" },
//        Science: { obtainedMarks: 85, grade: "A" },
//        English: { obtainedMarks: 88, grade: "A" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "Bob",
//      roll: "003",
//      registration: "2021003",
//      gender: "Male",
//      marks: {
//        Math: { obtainedMarks: 78, grade: "B+" },
//        Science: { obtainedMarks: 82, grade: "B+" },
//        English: { obtainedMarks: 75, grade: "B" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "Sarah",
//      roll: "004",
//      registration: "2021004",
//      gender: "Female",
//      marks: {
//        Math: { obtainedMarks: 95, grade: "A+" },
//        Science: { obtainedMarks: 88, grade: "A" },
//        English: { obtainedMarks: 92, grade: "A+" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "Mike",
//      roll: "005",
//      registration: "2021005",
//      gender: "Male",
//      marks: {
//        Math: { obtainedMarks: 70, grade: "B" },
//        Science: { obtainedMarks: 75, grade: "B" },
//        English: { obtainedMarks: 72, grade: "B-" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "Emily",
//      roll: "006",
//      registration: "2021006",
//      gender: "Female",
//      marks: {
//        Math: { obtainedMarks: 85, grade: "A" },
//        Science: { obtainedMarks: 80, grade: "A-" },
//        English: { obtainedMarks: 88, grade: "A" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "David",
//      roll: "007",
//      registration: "2021007",
//      gender: "Male",
//      marks: {
//        Math: { obtainedMarks: 78, grade: "B+" },
//        Science: { obtainedMarks: 82, grade: "B+" },
//        English: { obtainedMarks: 75, grade: "B" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "Sophia",
//      roll: "008",
//      registration: "2021008",
//      gender: "Female",
//      marks: {
//        Math: { obtainedMarks: 92, grade: "A+" },
//        Science: { obtainedMarks: 90, grade: "A+" },
//        English: { obtainedMarks: 85, grade: "A" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "James",
//      roll: "009",
//      registration: "2021009",
//      gender: "Male",
//      marks: {
//        Math: { obtainedMarks: 82, grade: "B+" },
//        Science: { obtainedMarks: 85, grade: "A" },
//        English: { obtainedMarks: 80, grade: "A-" },
//      },
//      result: "Pass",
//    },
//    {
//      name: "Lily",
//      roll: "010",
//      registration: "2021010",
//      gender: "Female",
//      marks: {
//        Math: { obtainedMarks: 95, grade: "A+" },
//        Science: { obtainedMarks: 92, grade: "A+" },
//        English: { obtainedMarks: 90, grade: "A+" },
//      },
//      result: "Pass",
//    },
//  ];
 
